version: "3.7"

services:
  lnd:
    image: crypdex/lnd:0.6
    restart: on-failure
    command:
      --litecoin.active
      --litecoin.mainnet
      --litecoin.node=litecoind
      --litecoind.rpchost=litecoin
      --litecoind.rpcuser=abc
      --litecoind.rpcpass=123
      --litecoind.zmqpubrawblock=tcp://litecoin:28333
      --litecoind.zmqpubrawtx=tcp://litecoin:28334
    depends_on:
      - litecoin
    volumes:
      - /Volumes/T5/data/lnd:/home/lnd/.lnd

  # Supporting services
  litecoin:
    image: crypdex/litecoin-core:0.17
    restart: on-failure
    command:
      -rpcuser=abc
      -rpcpassword=123
      -printtoconsole
      -txindex
    ports:
      - 9332:9332
    volumes:
      - /Volumes/T5/data/litecoin:/home/litecoin/.litecoin